exchanges:
  spot: 'BYBIT,GATEIO,KUCOIN,MEXC'
  swap: 'BYBIT,GATEIO,KUCOIN,MEXC'
  futures: ''
  #spot: 'BINANCE,BYBIT,GATEIO,KUCOIN,MEXC'
  #swap: 'BINANCE,BYBIT,GATEIO,KUCOIN,MEXC'
  #futures: 'BINANCE,BYBIT,GATEIO,KUCOIN,MEXC'

  # this property use when we fetch fundings for all tickers for one ticker will be used swap
  # because for some exchanges it can take a lot time
  fundings: 'BYBIT,GATEIO,BINANCE'

min_spread: 1